version: '3.7'
services:
  flask:
    build: .
    environment:
      FLASK_APP: app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - jaeger
    command: >
        sh -c "if [ ! -d migrations ]; then
            flask db init && flask db migrate && flask db upgrade;
        fi"
    networks:
      - backend

  postgres:
    image: latency-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres_logs:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - backend

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - flask
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata:
  postgres_logs:
