global:
  scrape_interval: 15s  # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'flask'
    static_configs:
      - targets: ['flask:5000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'jaeger'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['jaeger:16686']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
